version: "1.0"

# Example pipeline demonstrating signals: emit, skip, completed
# Uses a custom executor (mock-agent.sh) to simulate LLM responses.
#
# Signals exercised:
#   - emit:      setup step emits api_url for use in later prompts
#   - skip:      tasks containing "SKIP_ME" are skipped in the iterator loop
#   - completed: setup and implementation steps report completion
#   - reject:    review step rejects on round 1
#   - approve:   review step approves on round 2+

inputs:
  project_name: "example-project"

defaults:
  agent:
    tool: custom
    model: mock
    retry: 0
  iteration_delay_ms: 0

pipeline:
  # Step 1: Setup — emits api_url, signals completed
  - id: setup
    agent:
      prompt: prompts/write-code.md
      tool: custom
      script: ./scripts/mock-agent.sh

  # Step 2: Iterator loop over task files
  - id: dev
    loop:
      over: tasks/
      as: TASK
    steps:
      # Implementation step — checks for SKIP_ME marker
      - id: implement
        agent:
          prompt: prompts/write-code.md
          tool: custom
          script: ./scripts/mock-agent.sh

      # Review convergence loop — rejects round 1, approves round 2+
      - id: review-loop
        loop:
          until: APPROVE
          max_rounds: 5
        steps:
          - id: review
            agent:
              prompt: prompts/review-code.md
              tool: custom
              script: ./scripts/mock-agent.sh
