version: "1.0"

# Develop — implement pre-written tasks with review loop
#
# Usage:
#   1. Add task files to .pilot/session/tasks/
#   2. Run: pilot run

inputs:
  tasks_dir: session/tasks

defaults:
  agent:
    tool: claude-code
    model: opus
    retry: 1
  iteration_delay_ms: 2000

pipeline:
  # Phase 1: Analyze codebase — produce snapshot
  - id: analyze
    agent:
      prompt: prompts/analyze.md

  # Phase 2: Implement each task, then review/fix until approved
  - id: dev
    loop:
      over: "{{tasks_dir}}/"
      as: TASK
    steps:
      - id: implement
        agent:
          prompt: prompts/claude-implement.md

      - id: review-fix
        loop:
          until: APPROVE
          max_rounds: 3
        steps:
          - id: review
            agent:
              tool: codex
              model: gpt-5.3-codex
              prompt: prompts/codex-review.md
          - id: fix
            agent:
              prompt: prompts/fix.md
